version: '3'

services:

#  zipkin:
#    image: openzipkin/zipkin:latest
#    container_name: zipkin
#    ports:
#      - "9411:9411"
#    environment:
#      - STORAGE_TYPE=mem


#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/opt/bitnami/prometheus/prometheus.yml

  kong:
    image: kong/kong-gateway:3.5.0.2
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
#      KONG_ADMIN_GUI_URL: "0.0.0.0:8002"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
      - ./logs:/usr/local/kong/logs
    ports:
      - "8000:8000"
      - "8001:8001"
#      - "8002:8002"
